# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GithubMessanger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AlamofireImage'
  pod 'IQKeyboardManagerSwift'
  pod 'MBProgressHUD'
  pod 'MultilineTextField'
end
